### ISSUE TITLE
TranslationsException{msg: Locale "en_us" is not a valid BCP47 language tag. Try "en-US".}

### ISSUE THREAD

**Issue by okdevy** [marcglasberg/async_redux_core#1]
Hello, having an issue in async_redux flutter.  Actions are throwing UserException fatal error:
TranslationsException{msg: Locale "en_us" is not a valid BCP47 language tag. Try "en-US".}
  
I think it happens because of lib/src/user_exception_i18n.dart:

4. static final _t = Translations.byText('**en_us**') 

The documentation for i18n_extension tells:

```
// Will throw: Locale "en_us" should be "en-US" 
Translations.byText('en_us') + // Wrong!
   {
      'en_us': 'Hello, how are you?',  // Wrong!
      'pt_br': 'Olá, como vai você?',  // Wrong!
      'es': '¿Hola! Cómo estás?',
      'fr': 'Salut, comment ca va?',
      'de': 'Hallo, wie geht es dir?',
   };
```
   
```
// This is an example of a VALID and correct translation definition:
Translations.byText('en-US') +
   {
      'en-US': 'Hello, how are you?',
      'pt-BR': 'Olá, como vai você?',
      'es': '¿Hola! Cómo estás?',
      'fr': 'Salut, comment ca va?',
      'de': 'Hallo, wie geht es dir?',
   };
```

Thank you in advance.

**Comment by marcglasberg** [comment]
Fixed in:
`async_redux_core: ^1.3.1`
`async_redux: ^24.0.3`

Could you please try it out and let me know if it's now working? Thank you.

**Comment by okdevy** [comment]
Problem solved.

Thanks.
